Universe 	= vanilla
Executable 	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/RunEtaShiftStudy.sh
Arguments       =  /sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros /sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/MC/Jet30_data/lists_25_per_file/calo_seg_0_to_24.list /sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/MC/Jet30_data/lists_25_per_file/global_seg_0_to_24.list /sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/MC/Jet30_data/lists_25_per_file/jet_seg_0_to_24.list /sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/MC/Jet30_data/lists_25_per_file/truth_seg_0_to_24.list /sphenix/user/sgross/install_dir
Output  	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/condor_file_dir/condor_Jet30_seg_0.out
Error 		= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/condor_file_dir/condor_Jet30_seg_0.err
Log  		= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterEnergyCorrelatorCommonTools/macros/condor_file_dir/condor_Jet30_seg_0.log
Initialdir  	=  ../data_output/
PeriodicHold 	= (NumJobStarts>=1 && JobStatus == 1)
accounting_group = group_sphenix.user
accounting_group_user =     sgross
request_memory = 8192MB
Priority = 90
job_lease_duration = 3600
Queue 1
